export {
  initCodec,
  encodeMessage,
  decodeMessage,
  compress,
  decompress,
  getCompiledSchema,
  getSchemaBytes,
  createNodeChangesMessage,
  createNodeChange,
  parseVariableId,
  encodePaintWithVariableBinding,
  encodeNodeChangeWithVariables,
  type NodeChange,
  type KiwiGUID as GUID,
  type KiwiColor as Color,
  type KiwiPaint as Paint,
  type VariableBinding,
  type ParentIndex,
  type FigmaMessage
} from '@open-pencil/core'
